import datetime
data1 = input('Введите 1 дату (гггг-мм-дд): ')
time1 = input('Введите 1 время (чч-мм-сс): ')
data2 = input('Введите 2 дату (гггг-мм-дд): ')
time2 = input('Введите 2 время (чч-мм-сс): ')
a1 = data1.split('-')
b1 = data2.split('-')
a2 = time1.split('-')
b2 = time2.split('-')
a3 = datetime.datetime(int(a1[0]),int(a1[1]),int(a1[2]),int(a2[0]),int(a2[1]),int(a2[2]))
b3 = datetime.datetime(int(b1[0]),int(b1[1]),int(b1[2]),int(b2[0]),int(b2[1]),int(b2[2]))
sum = abs(a3-b3)
print(sum)